In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('sentiment.csv',encoding = "ISO-8859-1")

In [3]:
data1=pd.DataFrame(columns=['target','tweets'])

In [4]:
d1=data.iloc[:,0:1]
data1['target']=d1['0']
d2=data.iloc[:,5:10]
data1['tweets']=d2[0:1599999]
data1.head()

target                                             tweets
0       0  is upset that he can't update his Facebook by ...
1       0  @Kenichan I dived many times for the ball. Man...
2       0    my whole body feels itchy and like its on fire 
3       0  @nationwideclass no, it's not behaving at all....
4       0                      @Kwesidei not the whole crew

In [5]:
new_data=data1[0:10000]

In [6]:

###Drop Nan Values
new_data=new_data.dropna()

In [7]:
x=new_data['tweets']
y=new_data['target']

In [8]:
x.shape

(10000,)

In [9]:
y.shape

(10000,)

In [10]:

import tensorflow as tf

In [11]:
tf.__version__

'1.13.1'

In [12]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [13]:
voc_size=5000

In [14]:
messages=new_data.copy()

In [15]:
import nltk
import re
from nltk.corpus import stopwords

In [16]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['tweets'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088


3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762


5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361
5362
5363
5364
5365
5366
5367
5368
5369
5370
5371
5372
5373
5374
5375
5376
5377
5378
5379
5380
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394
5395
5396
5397
5398
5399
5400
5401
5402
5403
5404
5405
5406
5407
5408
5409
5410
5411
5412
5413
5414
5415
5416
5417
5418
5419
5420
5421
5422
5423


6871
6872
6873
6874
6875
6876
6877
6878
6879
6880
6881
6882
6883
6884
6885
6886
6887
6888
6889
6890
6891
6892
6893
6894
6895
6896
6897
6898
6899
6900
6901
6902
6903
6904
6905
6906
6907
6908
6909
6910
6911
6912
6913
6914
6915
6916
6917
6918
6919
6920
6921
6922
6923
6924
6925
6926
6927
6928
6929
6930
6931
6932
6933
6934
6935
6936
6937
6938
6939
6940
6941
6942
6943
6944
6945
6946
6947
6948
6949
6950
6951
6952
6953
6954
6955
6956
6957
6958
6959
6960
6961
6962
6963
6964
6965
6966
6967
6968
6969
6970
6971
6972
6973
6974
6975
6976
6977
6978
6979
6980
6981
6982
6983
6984
6985
6986
6987
6988
6989
6990
6991
6992
6993
6994
6995
6996
6997
6998
6999
7000
7001
7002
7003
7004
7005
7006
7007
7008
7009
7010
7011
7012
7013
7014
7015
7016
7017
7018
7019
7020
7021
7022
7023
7024
7025
7026
7027
7028
7029
7030
7031
7032
7033
7034
7035
7036
7037
7038
7039
7040
7041
7042
7043
7044
7045
7046
7047
7048
7049
7050
7051
7052
7053
7054
7055
7056
7057
7058
7059
7060
7061
7062
7063
7064
7065
7066
7067
7068
7069
7070


8527
8528
8529
8530
8531
8532
8533
8534
8535
8536
8537
8538
8539
8540
8541
8542
8543
8544
8545
8546
8547
8548
8549
8550
8551
8552
8553
8554
8555
8556
8557
8558
8559
8560
8561
8562
8563
8564
8565
8566
8567
8568
8569
8570
8571
8572
8573
8574
8575
8576
8577
8578
8579
8580
8581
8582
8583
8584
8585
8586
8587
8588
8589
8590
8591
8592
8593
8594
8595
8596
8597
8598
8599
8600
8601
8602
8603
8604
8605
8606
8607
8608
8609
8610
8611
8612
8613
8614
8615
8616
8617
8618
8619
8620
8621
8622
8623
8624
8625
8626
8627
8628
8629
8630
8631
8632
8633
8634
8635
8636
8637
8638
8639
8640
8641
8642
8643
8644
8645
8646
8647
8648
8649
8650
8651
8652
8653
8654
8655
8656
8657
8658
8659
8660
8661
8662
8663
8664
8665
8666
8667
8668
8669
8670
8671
8672
8673
8674
8675
8676
8677
8678
8679
8680
8681
8682
8683
8684
8685
8686
8687
8688
8689
8690
8691
8692
8693
8694
8695
8696
8697
8698
8699
8700
8701
8702
8703
8704
8705
8706
8707
8708
8709
8710
8711
8712
8713
8714
8715
8716
8717
8718
8719
8720
8721
8722
8723
8724
8725
8726


In [17]:
corpus

['upset updat facebook text might cri result school today also blah',
 'kenichan dive mani time ball manag save rest go bound',
 'whole bodi feel itchi like fire',
 'nationwideclass behav mad see',
 'kwesidei whole crew',
 'need hug',
 'loltrish hey long time see ye rain bit bit lol fine thank',
 'tatiana k nope',
 'twittera que muera',
 'spring break plain citi snow',
 'pierc ear',
 'caregiv bear watch thought ua loss embarrass',
 'octolinz count idk either never talk anymor',
 'smarrison would first gun realli though zac snyder doucheclown',
 'iamjazzyfizzl wish got watch miss iamlilnicki premier',
 'holli death scene hurt sever watch film wri director cut',
 'file tax',
 'lettya ahh ive alway want see rent love soundtrack',
 'fakerpattypattz oh dear drink forgotten tabl drink',
 'alydesign day get much done',
 'one friend call ask meet mid valley today time sigh',
 'angri barista bake cake ate',
 'week go hope',
 'blagh class tomorrow',
 'hate call wake peopl',
 'go cri sleep watch 

In [18]:

onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2390, 2120, 1470, 2092, 23, 2466, 4706, 110, 1852, 4196, 711],
 [1973, 284, 447, 2570, 3688, 2034, 4234, 1713, 3197, 4447],
 [204, 4860, 3688, 4706, 3259, 3938],
 [4453, 3816, 2135, 1155],
 [3735, 204, 3113],
 [275, 557],
 [1854, 2722, 2170, 2570, 1155, 2472, 1915, 2433, 2433, 1027, 4515, 1637],
 [4854, 4605, 2581],
 [4889, 2890, 2491],
 [1274, 399, 584, 3699, 923],
 [3320, 4844],
 [4138, 2104, 3977, 2266, 268, 3936, 4565],
 [2223, 1516, 2176, 2659, 3665, 3252, 565],
 [2021, 1757, 3944, 3109, 2006, 3087, 3824, 3245, 3848],
 [4979, 4774, 832, 3977, 167, 129, 1741],
 [3318, 3259, 4710, 197, 4937, 3977, 569, 4515, 3516, 3009],
 [4110, 901],
 [1317, 3975, 2727, 610, 4369, 1155, 1414, 3349, 117],
 [4581, 1328, 2978, 3115, 381, 4367, 3115],
 [4427, 1306, 108, 4115, 1845],
 [3249, 2563, 1115, 3053, 236, 3266, 4274, 1852, 2570, 4781],
 [4317, 2849, 2617, 4358, 2657],
 [123, 3197, 2727],
 [3879, 735, 909],
 [77, 1115, 1182, 4402],
 [3197, 2466, 154, 3977, 2858],
 [4259, 4166, 167, 804],
 [208

In [19]:

sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1852 4196  711]
 [   0    0    0 ... 1713 3197 4447]
 [   0    0    0 ... 4706 3259 3938]
 ...
 [   0    0    0 ... 4853 1253 3259]
 [   0    0    0 ... 3818 2831 1306]
 [   0    0    0 ... 3340 1239 1852]]


In [20]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0, 2390, 2120,
       1470, 2092,   23, 2466, 4706,  110, 1852, 4196,  711])

In [21]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
len(embedded_docs),y.shape

(10000, (10000,))

In [23]:

import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [24]:

X_final.shape,y_final.shape

((10000, 20), (10000,))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [26]:
from keras.callbacks import ModelCheckpoint

Using TensorFlow backend.


In [27]:
import os

In [28]:
checkpoint_path= "training_1/cp.ckpt"
checkpoint_dir= os.path.dirname(checkpoint_path)

In [29]:
cp_callback=tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True,verbose=1)

In [30]:
#checkpoint = ModelCheckpoint('model-{epoch:03d}.model',monitor='val_loss',verbose=0,save_best_only=True,mode='auto')
### Finally Training
p=model.fit(X_train,y_train,validation_data=(X_test,y_test),callbacks=[cp_callback],epochs=1,batch_size=64)

Train on 6700 samples, validate on 3300 samples
Instructions for updating:
Use tf.cast instead.
6656/6700 [============================>.] - ETA: 0s - loss: 0.0736 - acc: 0.9953
Epoch 00001: saving model to training_1/cp.ckpt

Consider using a TensorFlow optimizer from `tf.train`.
Instructions for updating:
Use tf.train.CheckpointManager to manage checkpoints rather than manually editing the Checkpoint proto.
6700/6700 [==============================] - 8s 1ms/sample - loss: 0.0731 - acc: 0.9954 - val_loss: 1.9433e-05 - val_acc: 1.0000


In [31]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [32]:

y_pred=model.predict_classes(X_test)

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,y_pred)

array([[1115, 2185],
       [   0,    0]], dtype=int64)

In [35]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.3378787878787879

In [36]:
y_pred.shape

(3300, 1)

In [70]:
import pickle

In [38]:
from tensorflow.keras.models import save_model, load_model

In [39]:
filepath= './saved_model'
save_model(model,filepath)

In [40]:
y_pred

array([[1],
       [1],
       [1],
       ...,
       [0],
       [1],
       [1]])